[package]
name = "beep_test"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
firewheel = { path = "../../", features = ["beep_test_node"] }
tracing.workspace = true
tracing-subscriber.workspace = true
